CREATE TABLE deviceId (
  id SERIAL PRIMARY KEY,
  deviceId VARCHAR(50) NOT NULL UNIQUE,
  userId INTEGER REFERENCES users(id) ON DELETE CASCADE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
